name: .NET MAUI

on:
  push:
    branches:
      - "main"
  

jobs:
  
  Build_iOS:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.1

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui
      - name: Restore NuGet
        run: |
          dotnet restore ./src
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build ./src -f net8.0-ios
        
