name: .NET MAUI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  
  Build_iOS:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build ./src -f net8.0-ios
          
  Build_MacCatalyst:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build macOS App
        run: |
          dotnet build ./src -f net8.0-maccatalyst

  